# Generated by Django 5.2.11 on 2026-02-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('diplome', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('cv_path', models.FileField(upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('competences_requises', models.TextField()),
                ('experience_min', models.IntegerField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.offre')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.user'),
        ),
    ]
