# Generated by Django 5.2.4 on 2026-04-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_offre_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='recruitment.subscriptionrequest'),
        ),
    ]
