# Generated by Django 5.2.4 on 2026-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_user_otp_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_submissions/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé')], default='En attente', max_length=50),
        ),
    ]
