# Generated by Django 5.2.4 on 2026-03-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidature_cv_file_alter_candidature_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='cv_path',
            new_name='cv_file',
        ),
    ]
