# Generated by Django 5.2.4 on 2026-04-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_offre_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='technical_name',
            field=models.SlugField(default='generic', help_text='Exemple: bankily ou masrvi (Aucun espace)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='transaction_ref',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
