# Generated by Django 5.2.4 on 2026-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recruitment', '0004_rename_cv_path_candidat_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='commentaire_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv_file',
            field=models.FileField(null=True, upload_to='cv_submissions/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('ADMIN', 'Responsable RH'), ('CANDIDAT', 'Candidat')], default='CANDIDAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
