# Generated by Django 5.2.4 on 2026-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_paymentmethod_technical_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
